services:
  nats:
    image: nats:alpine
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name main --jetstream --http_port 8222"
    volumes:
      - ~/jetstream-data:/tmp/nats/jetstream
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8222/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    image: ghcr.io/sunangel-project/api:latest
    ports:
      - "6660:6660"
    depends_on:
      nats:
        condition: service_healthy
    volumes:
      - .env:/.env
  
  spot-finder:
    image: ghcr.io/sunangel-project/spot-finder:latest
    depends_on:
      nats:
        condition: service_healthy
      api:
        condition: service_started
    volumes:
      - .env:/.env

  horizon-get:
    image: ghcr.io/sunangel-project/horizon-get:latest
    depends_on:
      nats:
        condition: service_healthy
      spot-finder:
        condition: service_started
    volumes:
      - .env:/.env

  horizon-compute:
    image: ghcr.io/sunangel-project/horizon-compute:latest
    depends_on:
      nats:
        condition: service_healthy
      horizon-get:
        condition: service_started
    volumes:
      - .env:/.env
    deploy:
      resources:
        limits:
          cpus: '0.8'
  
  sky-service:
    image: ghcr.io/sunangel-project/sky-service:latest
    depends_on:
      nats:
        condition: service_healthy
      horizon-compute:
        condition: service_started
    volumes:
      - .env:/.env
